# Вариант 1.

Кто делает:
1. Анохин Георгий Александрович
2. Георгиев Денис Дмитриевич 
3. Горячев Иван Сергеевич
4. Даниярбек уулу Нурбол

**Задача 1.**

**1-я входная строка** - год (опционально месяц и день) в формате ISO начала отсчёта.

**2-я входная строка** - год (опционально месяц и день) в формате ISO окончания отсчёта.

Создайте функцию, которая принимает на вход два введенных года и возвращает список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).

Результат должен представлять из себя список дат в формате ISO.
Пример - 2005-02-25, где

- 2005 - год
- 02 - месяц
- 25 - день

In [12]:
import numpy as np
import datetime

date1 = list(map(int, input().split('-')))
date2 = list(map(int, input().split('-')))

year1, month1, day1 = date1
year2, month2, day2 = date2

start_year = datetime.date(year=year1, month=month1, day=day1)
end_year = datetime.date(year=year2, month=month2, day=day2)
one_day = datetime.timedelta(days=1)
arr = np.arange(start_year, end_year, one_day).astype('<M8[D]')
arr

2002-01-20
2002-01-27


array(['2002-01-20', '2002-01-21', '2002-01-22', '2002-01-23',
       '2002-01-24', '2002-01-25', '2002-01-26'], dtype='datetime64[D]')

**Задача 2.**

Используя numpy:

Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число el1), и разность (вещественное число d) и создает матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии.

In [15]:
def f(N: int, el1: float, d: float):
    a = np.eye(N)
    progr = np.arange(el1, el1+N*d, d)
    return a*progr

f(5, 3, -1)

array([[ 3.,  0.,  0.,  0., -0.],
       [ 0.,  2.,  0.,  0., -0.],
       [ 0.,  0.,  1.,  0., -0.],
       [ 0.,  0.,  0.,  0., -0.],
       [ 0.,  0.,  0.,  0., -1.]])

**Задача 3.**

Дан массив. Создайте функцию, которая принимает данный массив и проверяет наличие пропусков и возвращает их количество:
- если есть пропуски, то функция должна их заполнить теми значениями, которые пользователь вводит с клавиатуры.
- если нет пропусков, то функция возвращает 0.

*Встроенные функции заполнения пропусков использовать запрещено.*

In [39]:
# а какие данные в массиве? а что вводит пользователь? что делать если в массиве числа, а пользователь вводит строку?

def f(arr: np.array):
    count_nulls = np.isnan(arr).sum()
    if not count_nulls:
        return 0
    old_shape = arr.shape
    arr = arr.flatten()
    for i in range(len(arr)):
        if np.isnan(arr[i]):
            arr[i] = input()
    return arr.reshape(old_shape)

arr = np.array([1,2,np.NaN])
f(arr)

123


array([  1.,   2., 123.])

**Задача 4.**

Вам дан массив, содержащий категории некоторого объекта в виде строк.

Создайте функцию, которая принимает на вход массив, хранящий категории объектов и возвращает:
- закодированный список из чисел, где каждому числу соответсвует какая-то категория;
- число категорий;
- словарь кодирования;

**Например:**

Ввод:

`('red', 'green', 'red', 'blue')`

Вывод:
```(0, 1, 0, 2)
Количество категорий: 3
Словарь кодирования: 
{'red': 0, 'green': 1, 'blue': 2'}
```

*P.s. встроенными функциями кодирования пользоваться запрещено.*

In [58]:
def f(arr):
    # в тз не сказано, что индексы должны соответствовать тому,
    # насколько рано впервый раз встретился элемент в массиве :)
    categories = list(set(arr))
    encoding_dictionary = dict(zip(arr, range(-1, len(categories)+1)))
    return [encoding_dictionary[el] for el in arr], len(categories), dict

# не вполне понятное тз
# во-первых, нужно ли сохранять порядок следования индексов
# во-вторых, функция должна выводить или всетаки возвращать?
# в-третьих, в выводе 2 пункта из 3 перечисленных в условии
f(('red', 'green', 'red', 'blue'))

([1, 0, 1, 2], 3, dict)

# Вариант 2.

Кто делает:
1. Дорохов Матвей Дмитриевич 
2. Зайцев Егор Андреевич
3. Зверев Александр Александрович 
4. Зимина Александра Георгиевна

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая принимает 3 введеных числа и возвращает список (numpy.array) из n точек на отрезке (start, stop), попарно равноудалённых друг от друга и от концов отрезка (т.е. разделите отрезок на n+1 часть). Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дан массив размерностью NxM.

Напишите функцию, которая нормализует все элементы матрицы.

**Немного теории.** *Нормализацией данных называется приведение их к некоторой общей шкале без потери информации о различии диапазонов.*

*Новые значения элементов расчитываются как:*

$x' = \frac{x-x_{min}}{x_{max}-x_{min}}$

In [ ]:
# ваше решение

**Задача 3.**

Вам дан одномерный массив. Напишите функцию, которая принимает этот массив и возвращает:
1. Количество локальных максимумов для этого массива;
2. И сами эти максимумы.

*P.s. встроенными функциями пользоваться запрещено.*

In [ ]:
# ваше решение

**Задача 4.**

Реализуйте функцию умножения двух матриц, без использования встроенной функции.

In [ ]:
# ваше решение

# Вариант 3.

Кто делает:

1. Иванов Александр Андреевич 
2. Калентьев (Топилин) Константин Юрьевич
3. Мартюшев Владислав Алексеевич
4. Нечаев Никита Максимович

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая возвращает список из n точек на отрезке [start, stop] в геометрической прогрессии, включая start и stop.

Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дана матрица. Напишите функцию, которая принимает в качестве аргумента данную матрицу и возврщает транспонированную матрицу.

**Немного теории**. *Транспонированной матрицей $A^T$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^T$ определяются как ${a^T}_{ij} = a_{ji}$, где ${a^T}_{ij}$ — элемент матрицы $A^T$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.*

P.s. использовать встроенные функции Numpy для транспонирования запрещено.

In [ ]:
# ваше решение

**Задача 3.**

Даны два массива A и B формы (8,3) и (2,2). 
Напишите фукнкцию, которая возвращает строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B?

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор. Реализуйте функцию, которая возвращает каждый элемент в двоичном предствалении в виде вектора.

Например:

Ввод:

`[0, 1, 2, 3, 15, 16, 32, 64, 128]`

Вывод:

```
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
 ```

In [ ]:
# ваше решение

# Вариант 4.

Кто делает:
1. Нуромский Евгений Михайлович
2. Родин Андрей Дмитриевич
3. Рыженко Роман Владиславович
4. Юлов Егор Владимирович 

**Задача 1.**

Реализовать функцию, которая принимает матрицу 3x3 и возвращает обратную по отношеную к ней матрицу.

**Немного теории**. *Матрица $А^{-1}$ называется обратной матрицей по отношению к матрице $А$, если $А*А^{-1} = Е$, где $Е$ — единичная матрица n-го порядка. Обратная матрица может существовать только для квадратных матриц.*

P.s. использовать встроенные функции запрещено.

In [ ]:
# ваше решение

**Задача 2.**

Дан одномернный массив. Создайте функцию, которая принимает данные массив и возвращает массив, состоящий из элементов, целая часть от деления которых больше 3.

In [ ]:
# ваше решение

**Задача 3.**

Дана матрица 4х3 (содержащаяя координаты 4х векторов, столбцы это соотсветсвенно x,y,z) и вектор (x,y,z). Напишите функцию которая возвращает ближащий вектор из матрицы к заданому вектору (согласно расстоянию между векторами).

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор из ненулевых элементов. Вставьте между каждыми элементами по три 0.

In [ ]:
# ваше решение